### ISSUE TITLE
РК 1

### ISSUE THREAD

**Issue by DPeshkoff** [frontend-park-mail-ru/2023_2_fanaty_elki#4]
- [x] некорректная ссылка на Swagger в ридми
- [x] можно зарегаться с логином/паролем, содержащим эмодзи
<img width="407" alt="Снимок экрана 2023-10-06 в 18 36 24" src="https://github.com/frontend-park-mail-ru/2023_2_fanaty_elki/assets/31134795/9b1a7d87-46b1-4915-9696-94d8cd8d6b4d">

- [x] валидация не обновляется + нет валидации пароля
<img width="338" alt="Снимок экрана 2023-10-06 в 18 37 19" src="https://github.com/frontend-park-mail-ru/2023_2_fanaty_elki/assets/31134795/86fc2deb-6359-4a95-8344-71ac1cf830a9">

- [x] нет favicon и нет title у страницы
- [x] разобраться, что делает preconnect
- [x] кажется, что нужно лучше попадать в регистрацию - сейчас это не очень очевидно делается через "войти" (мб текстовки поменять?)
<img width="257" alt="Снимок экрана 2023-10-06 в 18 39 34" src="https://github.com/frontend-park-mail-ru/2023_2_fanaty_elki/assets/31134795/9c1c8901-cac0-413e-bd40-1cc9c061b0f9">

- [x] можно ввести поисковый запрос и сделать его, но поиска пока нет. Давайте задизейблим все, что пока нельзя использоваить
<img width="748" alt="Снимок экрана 2023-10-06 в 18 41 42" src="https://github.com/frontend-park-mail-ru/2023_2_fanaty_elki/assets/31134795/ebf7fd52-4f82-4436-95be-b3560a5483f2">

- [x] разобраться с регуляркой для проверки почты

**Comment by LDK28** [comment]
<img width="1440" alt="image" src="https://github.com/frontend-park-mail-ru/2023_2_fanaty_elki/assets/66313699/6d366cb9-0570-4028-8217-6ec0fc57f817">
Оставляю пустым поле логина, а мне выдает, что неверный логин/пароль, как- будто надо показать, что нужно заполнить

**Comment by DPeshkoff** [comment]
РК пересдано, баллы накинул)
